[package]
name = "metal-ray-tracing-rs"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asger.nyman@alexandra.dk>"]
edition = "2018"

[dependencies]
cocoa = "0.18"
objc = "0.2.5"
winit = "0.17"
tobj = "0.1.6"
metal = { path = "metal_lib/" }